### ISSUE TITLE
actor model is exciting,but it is the next generation for celery or just another alternative??

### ISSUE THREAD

**Issue by aohan237** [celery/cell#20]
will you celery guys work a lot on it ?

or just a experimentation on actor model theory??

**Comment by aohan237** [comment]
also have you done some benchmarks vs celery now?

**Comment by auvipy** [comment]
hi, I have been experimenting it and trying to modernize the codes right now. celery is a very mature framework, so unless cell provide significant improvement to celery, we won't integrate it with celery but will continue to experiment and integrate in future

**Comment by aohan237** [comment]
ok，Thanks
